version: '3.4'

services:
  unitconverterdb:
    image: postgres

  unitconverter.api:
    image: ${DOCKER_REGISTRY-}unitconverterapi
    build:
      context: .
      dockerfile: UnitConverter/Dockerfile
volumes:
  postgres_data:
 