// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using UnitConverter.Api.Data;

#nullable disable

namespace UnitConverter.Api.Migrations
{
    [DbContext(typeof(ConversionRateDbContext))]
    partial class ConversionRateDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("UnitConverter.Api.Entities.ConversionRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Rate")
                        .HasColumnType("numeric");

                    b.Property<string>("UnitFrom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UnitTo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ConversionRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Rate = 1.8m,
                            UnitFrom = "Celsius",
                            UnitTo = "Fahrenheit"
                        },
                        new
                        {
                            Id = 2,
                            Rate = 0.621371m,
                            UnitFrom = "Kilometers",
                            UnitTo = "Miles"
                        },
                        new
                        {
                            Id = 3,
                            Rate = 2.20462m,
                            UnitFrom = "Kilograms",
                            UnitTo = "Pounds"
                        },
                        new
                        {
                            Id = 4,
                            Rate = 0.264172m,
                            UnitFrom = "Liters",
                            UnitTo = "Gallons"
                        },
                        new
                        {
                            Id = 5,
                            Rate = 3.28084m,
                            UnitFrom = "Meters",
                            UnitTo = "Feet"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
